services:
  app:
    container_name: nestjs-app
    build:
      context: .
    env_file:
      - .production.env
    ports:
      - '7000:7000'
    command: node dist/main.js
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .production.env
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5555:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
